name: Workers

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/workers.yml"
      - "src/**"
      - "workers/**"
      - ".env.production.gpg"
      - "package-lock.json"

defaults:
  run:
    shell: bash
    working-directory: "."

jobs:
  workers:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: |
          npm ci
      - name: Deploy
        if: success()
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PRODUCTION_PASSPHRASE" \
            --output .env.production .env.production.gpg

          cd workers
          for d in */; do
            echo "Deploying worker $d"
            (cd $d && npx @cloudflare/wrangler publish)
          done
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          PRODUCTION_PASSPHRASE: ${{ secrets.PRODUCTION_PASSPHRASE }}
